# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CenterLoss": "center_loss.ipynb",
         "FaceClassificationDataset": "datasets.ipynb",
         "FaceVerificationDataset": "datasets.ipynb",
         "main": "face_class_ver.ipynb",
         "fit_predict": "hyper_p_opt.ipynb",
         "MobileNetV2": "models_mobilenet.ipynb",
         "Conv2dAuto": "models_resnet.ipynb",
         "conv3x3": "models_resnet.ipynb",
         "conv": "models_resnet.ipynb",
         "ResidualBlock": "models_resnet.ipynb",
         "ResNetResidualBlock": "models_resnet.ipynb",
         "conv_bn": "models_resnet.ipynb",
         "ResNetBasicBlock": "models_resnet.ipynb",
         "ResNetBottleNeckBlock": "models_resnet.ipynb",
         "ResNetLayer": "models_resnet.ipynb",
         "ResNetEncoder": "models_resnet.ipynb",
         "ResnetDecoder": "models_resnet.ipynb",
         "resnet18": "models_resnet.ipynb",
         "resnet34": "models_resnet.ipynb",
         "resnet50": "models_resnet.ipynb",
         "ResNetN": "models_resnet.ipynb"}

modules = ["losses.py",
           "datasets.py",
           "face_class_ver.py",
           "hyperoptimization.py",
           "kaggle_data_setup.py",
           "models/mobilenet.py",
           "models/resnet.py"]

doc_url = "https://alejandroxag.github.io/axa_hw2p2/"

git_url = "https://github.com/alejandroxag/axa_hw2p2/tree/master/"

def custom_doc_links(name): return None
