# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CenterLoss": "center_loss.ipynb",
         "FaceClassificationDataset": "datasets.ipynb",
         "FaceVerificationDataset": "datasets.ipynb",
         "fit_predict": "hyper_p_opt.ipynb",
         "MobileNetV2": "models.ipynb"}

modules = ["losses.py",
           "datasets.py",
           "hyperoptimization.py",
           "kaggle_data_setup.py",
           "models.py"]

doc_url = "https://alejandroxag.github.io/axa_hw2p2/"

git_url = "https://github.com/alejandroxag/axa_hw2p2/tree/master/"

def custom_doc_links(name): return None
