# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CenterLoss": "face_class_ver.ipynb",
         "FaceClassificationDataset": "face_class_ver.ipynb",
         "FaceVerificationDataset": "face_class_ver.ipynb",
         "SIZE": "face_class_ver.ipynb",
         "NO_TRANSF": "face_class_ver.ipynb",
         "TRAIN_TRANSF": "face_class_ver.ipynb",
         "VAL_TRANSF": "face_class_ver.ipynb",
         "BasicBlock": "models_resnet2.ipynb",
         "Bottleneck": "models_resnet2.ipynb",
         "ResNet": "models_resnet2.ipynb",
         "create_dataloaders": "face_class_ver.ipynb",
         "fit_predict": "hyper_p_opt.ipynb",
         "main": "face_class_ver.ipynb",
         "parse_args": "face_class_ver.ipynb",
         "MobileNetV2": "models_mobilenet.ipynb",
         "Conv2dAuto": "models_resnet.ipynb",
         "conv3x3": "models_resnet.ipynb",
         "conv": "models_resnet.ipynb",
         "ResidualBlock": "models_resnet.ipynb",
         "ResNetResidualBlock": "models_resnet.ipynb",
         "conv_bn": "models_resnet.ipynb",
         "ResNetBasicBlock": "models_resnet.ipynb",
         "ResNetBottleNeckBlock": "models_resnet.ipynb",
         "ResNetLayer": "models_resnet.ipynb",
         "ResNetEncoder": "models_resnet.ipynb",
         "ResnetDecoder": "models_resnet.ipynb",
         "resnet18": "models_resnet.ipynb",
         "resnet34": "models_resnet.ipynb",
         "resnet50": "models_resnet.ipynb",
         "ResNetN": "models_resnet.ipynb"}

modules = ["losses.py",
           "datasets.py",
           "main.py",
           "hyperoptimization.py",
           "kaggle_data_setup.py",
           "models/mobilenet.py",
           "models/resnet.py",
           "models/resnet2.py"]

doc_url = "https://alejandroxag.github.io/hw2p2/"

git_url = "https://github.com/alejandroxag/hw2p2/tree/master/"

def custom_doc_links(name): return None
