# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SIZE": "face_recognition.ipynb",
         "NO_TRANSF": "face_recognition.ipynb",
         "TRAIN_TRANSF": "face_recognition.ipynb",
         "VAL_TRANSF": "face_recognition.ipynb",
         "FaceClassificationDataset": "face_recognition.ipynb",
         "FaceVerificationDataset": "face_recognition.ipynb",
         "create_dataloaders": "face_recognition.ipynb",
         "BasicBlock": "face_recognition.ipynb",
         "Bottleneck": "face_recognition.ipynb",
         "CenterlossFunc": "face_recognition.ipynb",
         "ResNet": "face_recognition.ipynb",
         "fit_and_log": "face_recognition.ipynb",
         "main": "face_recognition.ipynb",
         "parse_args": "face_recognition.ipynb",
         "parse_trials": "face_recognition.ipynb"}

modules = ["main.py",
           "kaggle_data_setup.py"]

doc_url = "https://alejandroxag.github.io/hw2p2/"

git_url = "https://github.com/alejandroxag/hw2p2/tree/master/"

def custom_doc_links(name): return None
