# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/kaggle_data_import.ipynb (unless otherwise specified).

__all__ = []

# Cell
# Data unziping

import os
from zipfile import ZipFile

print(os.getcwd())

with ZipFile('./data/competitions/11785-spring2021-hw2p2s1-face-classification/11785-spring2021-hw2p2s1-face-classification.zip', ) as zf: zf.extractall(path='./data/s1')

with ZipFile('./data/competitions/11785-spring2021-hw2p2s2-face-verification/11785-spring2021-hw2p2s2-face-verification.zip', ) as zf: zf.extractall(path='./data/s2')
